version: "3"

services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # ports:
    #   - 5432:5432
    env_file:
      - .env
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    image: backend
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - photo_volume:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    depends_on:
      - backend
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    depends_on:
      - frontend
    restart: always
    ports:
      - 80:80
# networks:
#   mini-ts:
#     driver: bridge

volumes:
  postgresql_volume:
    external: false
  photo_volume:
    external: false
